### ISSUE TITLE
RangeError: IPC ID must be between 0-9

### ISSUE THREAD

**Issue by not-ivy** [NextFire/apple-music-discord-rpc#12] opened 2022-03-07 06:10 UTC
Running on macOS Monterey version `12.2`, with deno version `1.19.2`.
Discord version: `Canary 117519 (c1e9073)`

Running `./music-rpc.ts` give me this error:
```
RangeError: IPC ID must be between 0-9
    at getIPCPath (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/util.ts:14:31)
    at findIPC (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/util.ts:30:16)
    at findIPC (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/util.ts:41:12)
    at async Function.connect (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/conn.ts:40:18)
    at async Client.connect (https://raw.githubusercontent.com/harmonyland/discord_rpc/ba127c20816af15e2c3cd2c17d81248b097e9bd2/src/client.ts:85:16)
    at async main (file:///Users/sourtaste000/Developer/apple-music-discord-rpc/music-rpc.ts:19:5)
```

**Comment by sourTaste000** [comment] 2022-03-07 06:17
Switching back to the stable version of discord(Stable 117300 (cc0861f) fixed the problem. Still do not know why this issue exists, maybe there is a breaking change of the IPC system?

**Comment by NextFire** [comment] 2022-03-07 10:52
I will not investigate issues regarding canary versions of Discord. Maybe only this version is at fault and I guess I can only recommend you to use the stable version for now….

**Comment by sourTaste000** [comment] 2022-03-13 05:22
This issue reappeared at the stable version of discord 😦
```
Stable 118205 (081ceba)
Host 0.0.265
OS X 10.15.7 (21.3.0)
```

**Comment by sourTaste000** [comment] 2022-03-13 05:36
Weird, when I restart discord, the problem is gone. Guess I'll have to restart discord when I counter this problem again

**Comment by JonathanX64** [comment] 2022-03-22 19:33
This error means that script was unable to detect Discord. 

I've ran into the same problem with LaunchAgent. It's solvable: you must ensure that script runs as user, not as root, and is put into ~/Library/LaunchAgents, not system-wide LaunchAgents.

Basically, when script runs as root, it is unable to detect Discord process that is run by user.

By the way, thank you NextFire for delivering this script, I really like using it.

**Comment by nikorue** [comment] 2022-03-27 05:23
kinda sad that canary isn't supported, because anything that canary breaks will sooner or later be on stable...

**Comment by NextFire** [comment] 2022-05-15 08:01
Closing it for now as it is still working on the stable version for two months now.

**Closed by NextFire** 2022-05-15 08:01 UTC
